# Generated by Django 4.2.17 on 2025-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripecheckoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('month1', 'Monthly'), ('month3', '3 Months'), ('month6', '6 Months'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
