# Generated by Django 4.2.17 on 2025-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplay', '0052_project_activity_skill_character_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=True)),
                ('upkeep', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(default='none', max_length=50)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='gameplay.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('friend', 'Friend'), ('rival', 'Rival'), ('mentor', 'Mentor'), ('enemy', 'Enemy'), ('ally', 'Ally'), ('romantic', 'Romantic'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('cousin', 'Cousin')], max_length=20)),
                ('strength', models.IntegerField(default=0)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('biological', models.BooleanField(default=True)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_as_char1', to='gameplay.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_as_char2', to='gameplay.character')),
            ],
            options={
                'unique_together': {('character1', 'character2', 'relationship_type')},
            },
        ),
    ]
