# Generated by Django 4.2.17 on 2025-02-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0061_character_is_pregnant_character_parents_and_more'),
        ('gameworld', '0003_alter_characterrelationship_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_birth_date', models.DateField(blank=True, null=True)),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('partner_is_pregnant', models.BooleanField(default=False)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner1_relationships', to='gameplay.character')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner2_relationships', to='gameplay.character')),
            ],
        ),
    ]
