# Generated by Django 4.2.17 on 2025-02-02 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gameworld", "0004_partnership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterprogression",
            name="date_started",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
