# Generated by Django 4.2.17 on 2025-02-08 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('gameworld', '0008_alter_characterprogression_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=6)),
                ('temperature', models.IntegerField()),
                ('crop_growth_modifier', models.FloatField(default=1.0)),
                ('travel_speed_modifier', models.FloatField(default=1.0)),
                ('cleanliness_modifier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_temperature', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_temp_change', models.IntegerField()),
                ('max_temp_change', models.IntegerField()),
                ('typical_duration', models.IntegerField(default=3)),
                ('crop_growth_modifier', models.FloatField(default=1.0)),
                ('travel_speed_modifier', models.FloatField(default=1.0)),
                ('cleanliness_modifier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='characterrelationship',
            name='character1',
        ),
        migrations.RemoveField(
            model_name='characterrelationship',
            name='character2',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='partner1',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='partner2',
        ),
        migrations.DeleteModel(
            name='CharacterProgression',
        ),
        migrations.DeleteModel(
            name='CharacterRelationship',
        ),
        migrations.DeleteModel(
            name='CharacterRole',
        ),
        migrations.DeleteModel(
            name='Partnership',
        ),
        migrations.AddField(
            model_name='weatherevent',
            name='weather_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameworld.weathertype'),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameworld.weatherevent'),
        ),
    ]
