# Generated by Django 4.2.17 on 2025-03-02 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameworld', '0011_gamecalendar_season_weatherevent_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newUsers', models.PositiveIntegerField(default=0)),
                ('questsCompleted', models.PositiveIntegerField(default=0)),
                ('activitiesCompleted', models.PositiveIntegerField(default=0)),
                ('activityTimeLogged', models.PositiveIntegerField(default=0)),
                ('recordDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GameWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('num_profiles', models.PositiveIntegerField(default=0)),
                ('highest_login_streak_ever', models.PositiveIntegerField(default=0)),
                ('highest_login_streak_current', models.PositiveIntegerField(default=0)),
                ('total_activity_num', models.PositiveIntegerField(default=0)),
                ('total_activity_time', models.PositiveIntegerField(default=0)),
                ('years_diff', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='GameCalendar',
        ),
    ]
