# Generated by Django 5.1.3 on 2024-11-20 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=1000)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/profile_pics/"
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=0)),
                ("total_time", models.IntegerField(default=0)),
                ("total_activities", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
