# Generated by Django 5.1.3 on 2024-11-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_rename_player_activity_profile_and_more'),
        ('users', '0002_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Profile',
        ),
    ]
