# Generated by Django 5.1.3 on 2024-11-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_player_profile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
