# Generated by Django 5.1.3 on 2024-11-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_character_questcompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questcompletion',
            name='character',
        ),
        migrations.RemoveField(
            model_name='questcompletion',
            name='quest',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='QuestCompletion',
        ),
    ]
