# Generated by Django 5.1.3 on 2024-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0032_buff_rename_rewards_questresults_dynamic_rewards_and_more'),
        ('users', '0013_profile_login_streak_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buffs',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='gameplay.buff'),
        ),
    ]
