# Generated by Django 4.2.17 on 2025-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_create_at_profile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
