# Generated by Django 4.2.17 on 2025-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
    ]
