# Generated by Django 4.2.17 on 2025-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_customuser_delete_at_customuser_pending_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_logins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
