# Generated by Django 4.2.17 on 2025-04-03 06:16

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_profile_total_logins"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
