# Generated by Django 4.2.17 on 2025-05-22 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitecode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
