# Generated by Django 4.2.22 on 2025-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_invitecode_created_at_invitecode_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
