# Generated by Django 4.2.22 on 2025-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_profile_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_confirmed",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
