# Generated by Django 4.2.22 on 2025-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_customuser_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
