# Generated by Django 4.2.22 on 2025-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_customuser_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
