# Generated by Django 4.2.22 on 2025-07-21 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_profile_deleted_at_profile_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
