name: 🚀 Feature Request
description: Suggest a new feature or improvement for Progress RPG
title: "[Feature Request] "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for **Progress RPG**! Please try to be as specific and constructive as possible — the more detail, the better.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature you're suggesting.
      placeholder: e.g. "Add a timer sound notification when the quest ends"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Explain what the feature does and how you'd expect it to work.
      placeholder: Describe what this feature is, what problem it solves, or what it adds to the user experience.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Tell us why this feature matters — how does it improve the experience or solve a current issue?
      placeholder: e.g. "Sometimes I forget the timer is running. A sound would help me stay on track."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context or screenshots
      description: Add any other context, related features, screenshots, or mockups that help explain your idea.
      placeholder: You can also link to similar tools or ideas you’ve seen elsewhere.

  - type: checkboxes
    id: agree
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
