# Generated by Django 4.2.22 on 2025-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancewindow",
            name="tasks_scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
