# Generated by Django 4.2.22 on 2025-06-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_management', '0002_maintenancewindow_tasks_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancewindow',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
