# Generated by Django 4.2.17 on 2025-02-07 21:56

from django.db import migrations


def migrate_character_data(apps, schema_editor):
    # Get the old Character model from 'gameplay' app
    OldCharacter = apps.get_model('gameplay', 'Character')
    # Get the new Character model from 'character' app
    NewCharacter = apps.get_model('character', 'Character')

    # Copy data from the old to the new model
    for old_character in OldCharacter.objects.all():
        new_character = NewCharacter(
            id=old_character.id,
            first_name=old_character.first_name,
            last_name=old_character.last_name,
            name=old_character.name,
            backstory=old_character.backstory,
            gender=old_character.gender,
            dob=old_character.dob,
            dod=old_character.dod,
            total_quests=old_character.total_quests,
        )
        new_character.save()
        print("Old character parents:", old_character.parents.all())
        new_character.parents.set(old_character.parents.values_list('id', flat=True))
        new_character.save()


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_character_data),
    ]
