# Generated by Django 4.2.17 on 2025-02-08 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('character', '0002_migrate_character_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('friend', 'Friend'), ('rival', 'Rival'), ('mentor', 'Mentor'), ('enemy', 'Enemy'), ('ally', 'Ally'), ('romantic', 'Romantic'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling')], max_length=20)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('strength', models.IntegerField(default=0)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('biological', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RomanticRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_childbirth_date', models.DateField(blank=True, null=True)),
                ('total_births', models.PositiveIntegerField(default=0)),
                ('partner_is_pregnant', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='dod',
            new_name='death_date',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.AddField(
            model_name='character',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='fertility',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='character',
            name='last_childbirth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.position'),
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CharacterRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterrole')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationshipMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterrelationshipmembership', to='character.character')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterrelationship')),
            ],
            options={
                'unique_together': {('character', 'relationship')},
            },
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='characters',
            field=models.ManyToManyField(through='character.CharacterRelationshipMembership', to='character.character'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='romantic_relationship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.romanticrelationship'),
        ),
        migrations.CreateModel(
            name='CharacterProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('base_progression_rate', models.PositiveIntegerField(default=1)),
                ('player_acceleration_factor', models.PositiveIntegerField(default=2)),
                ('date_started', models.DateField(default=django.utils.timezone.now)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.characterrole')),
            ],
        ),
    ]
