# Generated by Django 4.2.17 on 2025-02-13 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_characterrelationship_characterrole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterrelationship",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
