# Generated by Django 4.2.22 on 2025-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0006_alter_character_parents"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="can_link",
            field=models.BooleanField(default=False),
        ),
    ]
