# Generated by Django 5.1.3 on 2024-11-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_remove_questrequirement_quest_needed_and_more'),
        ('users', '0006_remove_questcompletion_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_completed', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.quest')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='quest_completions',
            field=models.ManyToManyField(related_name='completed_by', through='gameplay.QuestCompletion', to='gameplay.quest'),
        ),
    ]
