# Generated by Django 5.1.3 on 2024-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0008_alter_quest_description_alter_quest_number_stages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="user",
            new_name="profile",
        ),
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
