# Generated by Django 5.1.3 on 2024-11-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_alter_quest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.quest'),
        ),
    ]
