# Generated by Django 5.1.3 on 2024-11-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0015_alter_character_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="coins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
