# Generated by Django 5.1.3 on 2024-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0018_questcompletion_last_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
