# Generated by Django 5.1.3 on 2024-12-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0022_alter_quest_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="total_quests",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
