# Generated by Django 5.1.3 on 2024-12-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0023_character_total_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questtimer',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_timer', to='gameplay.character'),
        ),
        migrations.AlterField(
            model_name='questtimer',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
