# Generated by Django 5.1.3 on 2024-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0027_quest_stages_delete_queststage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='stages',
            field=models.JSONField(default=dict),
        ),
    ]
