# Generated by Django 5.1.3 on 2024-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0028_alter_quest_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='stages',
            field=models.JSONField(default=list),
        ),
    ]
