# Generated by Django 5.1.3 on 2024-12-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0029_alter_quest_stages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="stages",
        ),
    ]
