# Generated by Django 5.1.3 on 2024-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0031_quest_stages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default buff name", max_length=100)),
                (
                    "attribute",
                    models.CharField(default="Default buff attribute", max_length=50),
                ),
                ("duration", models.PositiveIntegerField(default=0)),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "buff_type",
                    models.CharField(
                        choices=[
                            ("additive", "Additive"),
                            ("multiplicative", "Multiplicative"),
                        ],
                        default="additive",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="questresults",
            old_name="rewards",
            new_name="dynamic_rewards",
        ),
        migrations.AddField(
            model_name="activity",
            name="xp_rate",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="questresults",
            name="buffs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="questresults",
            name="coin_reward",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questresults",
            name="xp_reward",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="buffs",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="gameplay.buff"
            ),
        ),
    ]
