# Generated by Django 5.1.3 on 2024-12-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0032_buff_rename_rewards_questresults_dynamic_rewards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="xp_modifier",
            field=models.FloatField(default=1),
        ),
    ]
