# Generated by Django 5.1.3 on 2024-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0034_appliedbuff_alter_quest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcompletion',
            name='last_completed',
            field=models.DateTimeField(),
        ),
    ]
