# Generated by Django 4.2.17 on 2024-12-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0036_alter_quest_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="xp_next_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
