# Generated by Django 4.2.17 on 2025-01-01 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0040_alter_dailystats_recorddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='recordDate',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
