# Generated by Django 4.2.17 on 2025-01-01 22:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0041_alter_dailystats_recorddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activitytimer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 22, 38, 41, 502793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='activitytimer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buff',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questrequirement',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questresults',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questtimer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 22, 38, 41, 502793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='questtimer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 22, 38, 41, 502793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 22, 38, 41, 502793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='buff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 22, 38, 41, 507801, tzinfo=datetime.timezone.utc)),
        ),
    ]
