# Generated by Django 4.2.17 on 2025-01-02 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0045_alter_activity_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameWorld",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 0, 31, 18, 506617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="dailystats",
            name="recordDate",
            field=models.DateField(default=datetime.date(2025, 1, 2)),
        ),
    ]
