# Generated by Django 4.2.17 on 2025-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0047_dailystats_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
