# Generated by Django 4.2.17 on 2025-01-09 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0048_alter_dailystats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='recordDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
