# Generated by Django 4.2.17 on 2025-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0049_alter_dailystats_recorddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="intro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="quest",
            name="outro_text",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
