# Generated by Django 4.2.17 on 2025-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0051_alter_quest_description_alter_quest_intro_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='gameplay.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
    ]
