# Generated by Django 4.2.17 on 2025-02-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0057_character_backstory_character_dob_character_dod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="role",
        ),
    ]
