# Generated by Django 4.2.17 on 2025-02-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0058_remove_character_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="dod",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
