# Generated by Django 4.2.17 on 2025-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0061_character_is_pregnant_character_parents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="is_npc",
            field=models.BooleanField(default=True),
        ),
    ]
