# Generated by Django 4.2.17 on 2025-02-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0065_remove_quest_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="location",
        ),
        migrations.RemoveField(
            model_name="character",
            name="x_coordinate",
        ),
        migrations.RemoveField(
            model_name="character",
            name="y_coordinate",
        ),
    ]
