# Generated by Django 4.2.17 on 2025-02-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0068_character_quest_completions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='buffs',
        ),
        migrations.RemoveField(
            model_name='character',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quest_completions',
        ),
        migrations.RemoveField(
            model_name='playercharacterlink',
            name='character',
        ),
        migrations.RemoveField(
            model_name='playercharacterlink',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='questcompletion',
            name='character_wip',
        ),
    ]
