# Generated by Django 4.2.17 on 2025-02-09 13:59

from django.db import migrations, models
import gameplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0072_remove_quest_default_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='duration_choices',
            field=models.JSONField(default=gameplay.models.Quest.default_duration_choices),
        ),
    ]
