# Generated by Django 4.2.17 on 2025-02-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0072_remove_quest_default_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="xp_rate",
            field=models.IntegerField(default=1),
        ),
    ]
