# Generated by Django 4.2.17 on 2025-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0076_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcompletion',
            name='times_completed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
