# Generated by Django 4.2.17 on 2025-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0077_alter_questcompletion_times_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('empty', 'Empty')], default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='questtimer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('empty', 'Empty')], default='empty', max_length=20),
        ),
    ]
