# Generated by Django 4.2.17 on 2025-03-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0079_delete_dailystats_delete_gameworld'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questrequirement',
            unique_together={('quest', 'prerequisite')},
        ),
    ]
