# Generated by Django 4.2.17 on 2025-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0082_servermessage_delete_pendingnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermessage',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('server_message', 'Server Message'), ('action', 'Action'), ('response', 'Response'), ('error', 'Error'), ('notification', 'Notification')], max_length=20),
        ),
    ]
