# Generated by Django 4.2.17 on 2025-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0083_alter_servermessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedbuff',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
