# Generated by Django 4.2.22 on 2025-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0084_appliedbuff_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='duration_choices',
            field=models.JSONField(default=[300, 600, 900, 1200, 1500, 1800]),
        ),
    ]
