# Generated by Django 4.2.22 on 2025-06-14 21:23

from django.db import migrations, models
import gameplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0085_alter_quest_duration_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='duration_choices',
            field=models.JSONField(default=gameplay.models.Quest.default_duration_choices),
        ),
    ]
