# Generated by Django 4.2.22 on 2025-06-14 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0086_alter_quest_duration_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcompletion',
            name='last_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
