# Generated by Django 4.2.22 on 2025-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0087_alter_questcompletion_last_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='servermessage',
            name='group',
            field=models.CharField(default='', help_text='WebSocket group to send this message to.', max_length=50),
            preserve_default=False,
        ),
    ]
