# Generated by Django 4.2.22 on 2025-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0088_remove_servermessage_profile_servermessage_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermessage",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
