# Generated by Django 4.2.22 on 2025-06-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0089_servermessage_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermessage',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
