# Generated by Django 4.2.22 on 2025-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0090_alter_servermessage_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servermessage",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
