# Generated by Django 4.2.22 on 2025-07-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0091_alter_servermessage_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="canRepeat",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
