# Generated by Django 4.2.22 on 2025-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0092_alter_quest_canrepeat_alter_quest_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='stagesFixed',
            field=models.BooleanField(default=False),
        ),
    ]
