# Generated by Django 4.2.22 on 2025-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0093_quest_stagesfixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytimer",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questtimer",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
