# Generated by Django 4.2.22 on 2025-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0094_activitytimer_completed_at_questtimer_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitytimer",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="questtimer",
            name="completed_at",
        ),
        migrations.AddField(
            model_name="activity",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
