# Generated by Django 4.2.22 on 2025-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0095_remove_activitytimer_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="xp_gained",
            field=models.IntegerField(default=0),
        ),
    ]
